### PR TITLE
Sync2

### PR DESCRIPTION
**Pull request by 1313ou**

### CODE REVIEW

**Comment by krasi0** [comment]
Hey @1313ou ! Do you have an idea when you'll be able to merge this PR? I really need the new data from upstream to be merged in and the `wndb` files to be regenerated. 
Thanks and keep up the good work! :)

**Comment by 1313ou** [comment]
Probably tomorrow.  I need to rework injection of sentence templates that
was left out by upstream.

**Comment by krasi0** [comment]
Awesome 👍

**Comment by 1313ou** [comment]
Sorry i'm running into trouble with the gwn tool that seems to be unmaintained. I'm thinking of bypassing this by writing a less arcane tool for wndb generation.

**Comment by krasi0** [comment]
Sure. Whatever works for you

**Comment by krasi0** [comment]
@1313ou  Yay! The merge is now done. Were there many conflicts to resolve or did everything go smoothly?

**Comment by 1313ou** [comment]
The only conflict was the .gitignore actually. The *src* is imported as is
from upstream. The problem was elsewhere in the generation of derived data.
*xsrc *was generated without difficulty along the same lines. But the new
thing is the *grinder* that converts xml xsrc to *wndb* format. Originally
I used *gwn-scala-api* but that proved unreliable, unwieldy, arcane and
apparently unmaintained. The grinder was written from scratch and even if
the automated parse tests passed, I'll have to have a closer look in the
days to come. The Sqlite3 db was also generated successfully and and I now
can test in my Semantikos-English WordNet Android app. So I am reasonable
optimistic but it would be wise to consider the grinder *beta* until
further testing is carried out.

**Comment by krasi0** [comment]
Okay, I see. Thanks!
 Tomorrow, I am going to replace the 3.1 version files in my environment
and check if everything is working correctly with the newly generated data.

**Comment by krasi0** [comment]
I am using wordnet via python3 + NLTK, so, I've just replaced the Wordnet v3.1 files in my ~/nltk_data/corpora/wordnet
`adj.exc  cntlist      data.adj   data.verb  frames.vrb  index.noun   lexnames     sents.vrb
adv.exc  cntlist.rev  data.adv   dbfiles    index.adj   index.sense  noun.exc     verb.exc
build    cousin.exc   data.noun  dict       index.adv   index.verb   sentidx.vrb  verb.Framestext`
with the files from this repository's `wndb/` dir:
`adj.exc  build     data.adv   data.verb   index.sense  noun.exc     sents.vrb
adv.exc  data.adj  data.noun  frames.vrb  lexnames     sentidx.vrb  verb.exc`.

But when I import wordnet and try to get the definitions for a couple of synsets, I am getting various errors. As if the data is corrupted, e.g. see the snippet below.
Am I missing something in the process? Please advise :)

```
>>> from nltk.corpus import wordnet as wn; 
>>> from inspect import getmembers
>>> from pprint import pprint
>>> 
>>> print(wn.synset('sawtoothed-edged.s.01').definition()) 
Traceback (most recent call last):
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1404, in _synset_from_pos_and_line
    columns_str, gloss = data_file_line.strip().split('|')
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1348, in synset
    synset = self.synset_from_pos_and_offset(pos, offset)
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1382, in synset_from_pos_and_offset
    synset = self._synset_from_pos_and_line(pos, data_file_line)
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1488, in _synset_from_pos_and_line
    raise WordNetError('line %r: %s' % (data_file_line, e))
nltk.corpus.reader.wordnet.WordNetError: line 'ille "a frank courageous heart...triumphed over pain"- William Wordsworth "set a courageous example by leading them safely into and out of enemy-held territory"\n': not enough values to unpack (expected 2, got 1)
>>> print(wn.synset('sawtoothed-edged.s.01'))              
Traceback (most recent call last):
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1404, in _synset_from_pos_and_line
    columns_str, gloss = data_file_line.strip().split('|')
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1348, in synset
    synset = self.synset_from_pos_and_offset(pos, offset)
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1382, in synset_from_pos_and_offset
    synset = self._synset_from_pos_and_line(pos, data_file_line)
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1488, in _synset_from_pos_and_line
    raise WordNetError('line %r: %s' % (data_file_line, e))
nltk.corpus.reader.wordnet.WordNetError: line 'ille "a frank courageous heart...triumphed over pain"- William Wordsworth "set a courageous example by leading them safely into and out of enemy-held territory"\n': not enough values to unpack (expected 2, got 1)
>>> 
>>> 
>>> print(wn.synset('Hawaii_Volcanoes_National_Park.n.0').definition())
Traceback (most recent call last):
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1422, in _synset_from_pos_and_line
    lexname_index = int(_next_token())
ValueError: invalid literal for int() with base 10: '~i'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1348, in synset
    synset = self.synset_from_pos_and_offset(pos, offset)
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1382, in synset_from_pos_and_offset
    synset = self._synset_from_pos_and_line(pos, data_file_line)
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1488, in _synset_from_pos_and_line
    raise WordNetError('line %r: %s' % (data_file_line, e))
nltk.corpus.reader.wordnet.WordNetError: line '0000 ~i 09077126 n 0000 ~i 09077650 n 0000 ~i 09079430 n 0000 ~i 09083373 n 0000 ~i 09085161 n 0000 ~i 09087376 n 0000 ~i 09089018 n 0000 | the capital city of a political subdivision of a country\n': invalid literal for int() with base 10: '~i'
```

**Comment by 1313ou** [comment]
Works fine for me. 

pip3 install --user -U nltk
with data in <userdir>/ntlk_data
These yield correct results:

```
print(wn.synset('sawtoothed-edged.s.01'))
print(wn.synset('sawtoothed-edged.s.01').definition()) 

print(wn.synset('spread.n.1'))
print(wn.synset('spread.n.1').definition())

print(wn.synset('spread.v.1'))
print(wn.synset('spread.v.1').definition())

print(wn.synset('spread.v.2'))
print(wn.synset('spread.v.2').definition())

print(wn.synset('spread.v.3'))
print(wn.synset('spread.v.3').definition())

print(wn.synset('spread.v.4'))
print(wn.synset('spread.v.4').definition())

print(wn.synset('spread_eagle.n.1'))
print(wn.synset('spread_eagle.n.1').definition())

print(wn.synset('spread_eagle.n.2'))
print(wn.synset('spread_eagle.n.2').definition())
```

**Except for Hawaii**

But see
https://github.com/globalwordnet/english-wordnet/issues/165
https://github.com/globalwordnet/english-wordnet/issues/162

While retrieving the synset, NTLK correctly retrieves the line
data_file_line==
`08533041 15 n 02 Hawai'i_Volcanoes_National_Park 0 Hawaii_Volcanoes_National_Park 0 002 @i 08528127 n 0000 #p 09008034 n 0000 | a national park in Hawaii featuring active volcanoes
`
NTLK seems to be puzzled by the first member with an apostrophe in its middle;

line 1510:    
lemma_name = synset._lemmas[0]._name.lower() 
# value=hawai'i_volcanoes_national_park

line 1511: FAILS    
offsets = self._lemma_pos_offset_map[lemma_name][synset._pos]

I am investigating to see where the fault is. But the data seems ok for me.

**Comment by krasi0** [comment]
OK, weird. I just tried the following:in a brand new docker image, I installed wordnet 3.0, via 
python3 -m pip install --user -U nltk

```>>> import nltk
>>> nltk.download()
NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> wordnet
    Downloading package wordnet to /home/krasi0/nltk_data...
      Unzipping corpora/wordnet.zip.


# then started python3 again and checked if WN 3.0 is working properly:
from nltk.corpus import wordnet as wn;
  
print(wn.synset('sawtoothed-edged.s.01').definition())  
(of leaves) having an edged resembling a sawtooth



# then exited python3  
cp wndb/* nltk_data/corpora/wordnet/
# where wndb/ contains the files from your repository english-wordnet-master/wndb (re-downloaded right now again just in case)

# tried again to retrive the above synset definition:
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)  
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk.corpus import wordnet as wn;
>>>     
... print(wn.synset('sawtoothed-edged.s.01').definition())
Traceback (most recent call last):
  File "/home/krasi0/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1404, in _synset_from_pos_and_line
    columns_str, gloss = data_file_line.strip().split('|')
ValueError: not enough values to unpack (expected 2, got 1)```

So I must be missing some step in between?

**Comment by 1313ou** [comment]
I think I have found 2 problems:
-the index.noun|verb|adj|adv were not published on github because upstream gitignored them and this was inherited no questions asked (I had not noticed and my tests relied on my local data)
-the index files need to have a lower-cased index key. This is fixed now. My mistake again.

Otherwise your tests now run and NTLK is not to blame.

Replace you local data with newly-ground wndb. Your tests should work fine.

Sorry for lost time and thanks for your feedback.

**Comment by krasi0** [comment]
Ah, don't you worry about it! Such things happen all the time. It's now
working perfectly. Thanks again for your hard work :)

>>> print(wn.synset('sawtoothed-edged.s.01').definition())
(of leaves) having an edge resembling a sawtooth
>>> print(wn.synset('Hawaii_Volcanoes_National_Park.n.0').definition())
a national park in Hawaii featuring active volcanoes

**Pull request merged**
